[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "https://tsict.netlify.app/*"
  to = "https://care.techserveict.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tsict.netlify.app/*"
  to = "https://care.techserveict.com/:splat"
  status = 301
  force = true
