[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "https://tiis.netlify.com/*"
  to = "https://connect.techserveict.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tiis.netlify.com/*"
  to = "https://connect.techserveict.com/:splat"
  status = 301
  force = true
